services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    secrets:
      - openai_api_key
    environment:
      - FLASK_APP=/app/api/app.py
    volumes:
      - ./data/data-llm:/app/RAGeneration/data
      - ./data/database-llm:/app/RAGeneration/chroma
    network_mode: host

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    network_mode: host
  
secrets:
  openai_api_key:
    file: openai_api_key.txt