services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      args: # this way because -> https://github.com/vercel/next.js/discussions/14030
        NEXT_PUBLIC_API_URL: "http://localhost:5000"
    restart: always
    depends_on:
      - backend
    networks:
      - istoresumido_net
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
      args: # this way because -> https://github.com/vercel/next.js/discussions/14030
        CORS_ALLOWED_URL: "http://localhost:3000"
    restart: always
    secrets:
      - openai_api_key
    environment:
      - FLASK_APP=/app/api/app.py
      - REDIS_URL=redis://redis:6379
      - DEBUG=0
    depends_on:
      - redis
    volumes:
      - ./data/data-llm:/app/RAGeneration/data
      - ./data/database-llm:/app/RAGeneration/chroma
    networks:
      - istoresumido_net
    ports:
      - "5000:5000"

  redis:
    image: redis:latest
    restart: always
    networks:
      - istoresumido_net

secrets:
  openai_api_key:
    file: openai_api_key.txt

networks:
  istoresumido_net:
    driver: bridge

#! Example configuration for the server I have running
# networks:
#   cloudflare-tunnel-net:
#     name: network-coudflare-tunnel
#     external: true # because that docker network already exists
