version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    environment:
      - FLASK_APP=/app/api/app.py
    volumes:
      - ./data-llm:/app/RAGeneration/data
    network_mode: host

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    network_mode: host

  scrapy:
    build:
      context: ./crawler
      dockerfile: Dockerfile.crawler
    volumes:
      - ./data-llm:/app/00_downloads/
    network_mode: host
    command: ["scrapy", "crawl", "document_spider"]