services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    secrets:
      - openai_api_key
    environment:
      - FLASK_APP=/app/api/app.py
    volumes:
      - ./data/data-llm:/app/RAGeneration/data
      - ./data/database-llm:/app/RAGeneration/chroma
    networks:
      - cloudflare-tunnel-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    networks:
      - cloudflare-tunnel-net

secrets:
  openai_api_key:
    file: openai_api_key.txt

networks:
  cloudflare-tunnel-net:
    name: network-coudflare-tunnel
    external: true # because that docker network already exists


