FROM python:3.9-slim

WORKDIR /app

COPY api /app/api
COPY RAGeneration /app/RAGeneration

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# For documentation
EXPOSE 5000

ENV FLASK_APP=/app/api/app.py
CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:5000", "api.app:app"]